### ISSUE TITLE
Broken dependency

### ISSUE THREAD

**Issue by sbalayan1** [learn-co-curriculum/react-hooks-practice-animal-shelter#6]
### Canvas Link

https://github.com/learn-co-curriculum/react-hooks-practice-animal-shelter

### Concern

Starting the development server...

/home/seanbalayan/code/labs/JavaScript/react-hooks-practice-animal-shelter/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

TypeError: Cannot read properties of undefined (reading 'toString')
    at /home/seanbalayan/code/labs/JavaScript/react-hooks-practice-animal-shelter/node_modules/webpack/lib/cache/PackFileCacheStrategy.js:1217:53
    at async Promise.all (index 47)

### Additional Context

Students are unable to run npm start

**Comment by Matt-Eva** [comment]
Hey Sean!

Thanks for posting this. We don't currently have a fix for this problem, but we're looking into it.

We'd recommend not assigning this lab to students for the time being.

Thanks!
