### ISSUE TITLE
Error in running server

### ISSUE THREAD

**Issue by RuixDsgn** [learn-co-curriculum/react-hooks-practice-animal-shelter#7]
### Canvas Link

https://learning.flatironschool.com/courses/6443/assignments/242255?module_item_id=569303

### Concern

Ran into issues with loading the server when running npm start.

**Comment by Matt-Eva** [comment]
Hey @RuixDsgn!

Thanks for raising this issue! Was your error the same error as the one raised in this other issue? https://github.com/learn-co-curriculum/react-hooks-practice-animal-shelter/issues/6

If so, we've implemented a fix for it. Please sync your forked version with the new changes we've made in our repository and clone down this lab again.

If you keep experiencing problems, or need help getting set up with the lab again, please either

- Reach out to your instructor (if you've started the program and have an
  instructor)
- Use the
  [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit)
  feature in Canvas to connect with a Technical Coach on the Academic Success
  Team

Thank you!
